//
// Created by Konstantin Neureither on 09.07.20.
//

#ifndef COSMICTRIGGER_BUILDCOSMICTRAJTEMPLATESSCRIPT_H
#define COSMICTRIGGER_BUILDCOSMICTRAJTEMPLATESSCRIPT_H

void buildCosmicTemplatesScript(const int);



#endif //COSMICTRIGGER_BUILDCOSMICTRAJTEMPLATESSCRIPT_H
