//
// Created by Konstantin Neureither on 17.10.20.
//

#ifndef COSMICTRIGGER_BGANAPLOTS_EFFBEAMRATE_H
#define COSMICTRIGGER_BGANAPLOTS_EFFBEAMRATE_H

void BgAnaPlots_EffBeamRate();

#endif //COSMICTRIGGER_BGANAPLOTS_EFFBEAMRATE_H
