//
// Created by Konstantin Neureither on 15.09.20.
//

#ifndef COSMICTRIGGER_BGANAPLOTS_LEGACYSPC_H
#define COSMICTRIGGER_BGANAPLOTS_LEGACYSPC_H

void BgAnaPlots_legacySPC();

#endif //COSMICTRIGGER_BGANAPLOTS_LEGACYSPC_H
