//
// Created by Konstantin Neureither on 28.10.20.
//

#ifndef COSMICTRIGGER_CTTRAININGPLOTS_TEMPLATESSPC_H
#define COSMICTRIGGER_CTTRAININGPLOTS_TEMPLATESSPC_H

#endif //COSMICTRIGGER_CTTRAININGPLOTS_TEMPLATESSPC_H
