//
// Created by Konstantin Neureither on 28.10.20.
//

#ifndef COSMICTRIGGER_CTTRAININGPLOTS_TEMPLATESSPC_H
#define COSMICTRIGGER_CTTRAININGPLOTS_TEMPLATESSPC_H

void ctTrainingPlots_TemplatesSPC();

#endif //COSMICTRIGGER_CTTRAININGPLOTS_TEMPLATESSPC_H
